spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.31:3306/core_banking_service
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.31:8081/eureka
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
# /api-docs endpoint custom path
  api-docs:
    path: /api-docs
  # show-actuator: true
  # use-management-port: true
  # This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
# management:
#   endpoints:
#     web:
#       exposure:
#         include: openapi, swagger-ui
#   server:
#     port: 9090

info:
  app:
    name: ${spring.application.name}

app:
#  config:
#    keycloak:
#      server-url: http://localhost:9080/auth
#      realm: external
#      client-secret: ZXDnuEeRBoEDDF2rpwZyFHeyavqLf95Q
#      client-id: external-client
#  feign:
#    client:
#      core-service: core-service
  rabbitmq:
    exchange: microservices.exchange
    queue: microservices.queue
    routingkey: microservices.routingkey
    dynamic: False
