spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.31:3306/banking_core_user_service
    username: root
    password: P@ssw0rd
  jpa:
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://192.168.100.31:8180/realms/spring-boot
        registration:
          oidc:
            client-id: microservice-example
            client-secret: tKDcaOAHzwSvlJav3SUy1ooeLtD6w47b
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
      resourceserver:
        jwt:
          issuer-uri: http://192.168.100.31:8180/realms/spring-boot
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.31:8081/eureka
info:
  app:
    name: ${spring.application.name}
app:
  config:
    keycloak:
      server-url: http://192.168.100.31:8080/auth
      realm: spring-boot
      client-secret: tKDcaOAHzwSvlJav3SUy1ooeLtD6w47b
      client-id: microservices-example
  feign:
    client:
      core-banking: core-banking-service

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  # /api-docs endpoint custom path
  api-docs:
    path: /api-docs
  show-actuator: true
  use-management-port: true
  # This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui