spring:
  ## API SECURITY WITH KEYCLOAK PROVIDER
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            user-info-authentication-method: header
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          external-client:
            authorization-grant-type: authorization_code
            client-id: ${app.config.keycloak.client-id}
            client-secret: ${app.config.keycloak.client-secret}
            provider: keycloak
            redirect-uri: http://192.168.100.31:9080/login/oauth2/code/keycloak
            scope: openid
#          google:
#           clientId: <GOOGLE_CLIENT_ID>
#           clientSecret: <GOOGLE_CLIENT_SECRET>
#           redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
#           scope:
#             - email
#             - profile
#         facebook:
#           clientId: <FACEBOOK_CLIENT_ID>
#           clientSecret: <FACEBOOK_CLIENT_SECRET>
#           redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
#           scope:
#             - email
#             - public_profile
#         github:
#           clientId: <GITHUB_CLIENT_ID>
#           clientSecret: <GITHUB_CLIENT_SECRET>
#           redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
#           scope:
#             - user:email
#             - read:user
#       provider:
#         facebook:
#           authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
#           tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
#           userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
      resourceserver:
        jwt:
          issuer-uri : ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs

  ## GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## USER SERVICE
        - id: internet-banking-user-service
          uri: lb://internet-banking-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        ## FUND TRANSFER SERVICE
        - id: internet-banking-fund-transfer-service
          uri: lb://internet-banking-fund-transfer-service
          predicates:
            - Path=/fund-transfer/**
          filters:
            - StripPrefix=1
        ## CORE BANKING SERVICE
        - id: core-banking-service
          uri: lb://core-banking-service
          predicates:
            - Path=/banking-core/**
          filters:
            - StripPrefix=1
        ## UTILITY PAYMENTS SERVICE
        - id: internet-banking-utility-payment-service
          uri: lb://internet-banking-utility-payment-service
          predicates:
            - Path=/utility-payment/**
          filters:
            - StripPrefix=1

## SECURITY BASED CONFIGURATIONS
app:
  config:
    keycloak:
      url: http://192.168.100.31:9080/auth
      realm: external
      client-secret: 3fVwKTV12PLUaze22FkAm1UrVxZJABrB
      client-id: external-client

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.31:8081/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: 192.168.100.31
    prefer-ip-address: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  # /api-docs endpoint custom path
  api-docs:
    path: /api-docs
  # show-actuator: true
  # use-management-port: true
  # This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
# management:
#   endpoints:
#     web:
#       exposure:
#         include: openapi, swagger-ui
#   server:
#     port: 9090        

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
