server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://192.168.100.31:3306/banking_core_utility_payment_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.31:8081/eureka

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  # /api-docs endpoint custom path
  api-docs:
    path: /api-docs
  show-actuator: true
  use-management-port: true
  # This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui

info:
  app:
    name: ${spring.application.name}
