spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_user_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

app:
  config:
    keycloak:
      server-url: http://192.168.100.55:8080/auth
      realm: master
      clientId: microservices
      client-secret: Ef8azBeqTL21t0y1nZYjESldNplDmYrv
  feign:
    client:
      core-banking: core-banking-service
