spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.31:3306/banking_core_user_service
    username: root
    password: password
  jpa:
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQLDialect
#        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://localhost:8443/realms/external
        registration:
          oidc:
            client-id: external-client
            client-secret: 3fVwKTV12PLUaze22FkAm1UrVxZJABrB
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
      resourceserver:
        jwt:
          issuer-uri: http://192.168.100.31:9080/realms/external
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.31:8081/eureka
info:
  app:
    name: ${spring.application.name}

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  # /api-docs endpoint custom path
  api-docs:
    path: /api-docs
  # show-actuator: true
  # use-management-port: true
  # This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
# management:
#   endpoints:
#     web:
#       exposure:
#         include: openapi, swagger-ui
  server:
    port: 9090

app:
  config:
    keycloak:
      server-url: https://localhost:8443/auth
      realm: external
      client-secret: 3fVwKTV12PLUaze22FkAm1UrVxZJABrB
      client-d: external-client
  feign:
    client:
      core-banking: core-service